plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

ext {
    jfxVersion = '21.0.9'
    jacksonVer = '2.17.2'
    aparapiVer = '3.0.2'
}

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVer}"
    implementation "com.aparapi:aparapi:${aparapiVer}"
}

javafx {
    version = jfxVersion
    modules = [ 'javafx.controls', 'javafx.graphics', 'javafx.base', 'javafx.swing']
}

application {
    // Main.java 의 FQCN (패키지명 포함)
    mainClass = 'app.Main'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

